
export const metadata = {
<<<<<<< HEAD
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
=======
  title: 'Donapp'
}

export default function RootLayout({ children }) {
return (
>>>>>>> c674486757a712899f84514e8ce93c273b7f918e
    <html lang="en" >
      <body>{children}</body>
    </html>
  )
}
