import styles from "./../styles/register.module.css";

<<<<<<< HEAD
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({ children }) {
   return (
      <html lang="en" className={styles.fondo}>
        <body>{children}</body>
      </html>
    )
  }
  
=======
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
>>>>>>> c674486757a712899f84514e8ce93c273b7f918e
